"""Write arxiv-submission-notes.md: each paper's abstract as arXiv-ready text, and its Comments field."""
import re
import subprocess
from pathlib import Path

BASE = Path(__file__).resolve().parent
ABSTRACT_LIMIT = 1920

PAPERS = [
    ("ftap", "2606.28990", "v2", "The Fundamental Theorem of Asset Pricing, Formalized in Lean 4"),
    ("ito", "2606.15089", "v3", "A Machine-Checked Itô Calculus for Brownian Motion"),
    ("library", "2606.01356", "v4", "A Formally Verified Library of Mathematical Finance in Lean 4"),
]

COMMENTS = {
    "ftap": (
        "{pages} pages, 1 figure, 1 table. v2 corrects three statements of v1 (priority of the "
        "one-asset two-state case, the identification with the Esscher measure, and the claimed "
        "equivalence of no arbitrage and coercivity), adds the separation shared with coherent risk "
        "measures and the finite-state d-asset theorem, and describes release v1.5.0 of the Lean "
        "artifact: https://github.com/formal-applied-math/formal-mathfin"
    ),
    "ito": (
        "{pages} pages, 1 figure, 1 table. v3 adds Itô's formula under exponential growth with a "
        "named integrand, for C^3 functions without growth conditions (local-martingale form) and for "
        "Itô processes; martingale representation; agreement with the BrownianMotion package's "
        "stochastic integral; Girsanov and SDE applications; and corrects statements of v2 against the "
        "Lean source. Lean artifact (release v1.5.0): "
        "https://github.com/formal-applied-math/formal-mathfin"
    ),
    "library": (
        "{pages} pages, 4 tables. v4 describes release v1.5.0 (535 benchmark entries, about 100,000 "
        "lines of Lean), adds martingale representation, Itô processes, jump-diffusions, quantitative "
        "risk management and two contributed developments, and corrects several statements of v3. "
        "Lean artifact: https://github.com/formal-applied-math/formal-mathfin"
    ),
}

ACCENTS = [(r"It\^o", "Itô"), (r"Dol\'eans", "Doléans"), (r"L\'evy", "Lévy"), (r"num\'eraire", "numéraire")]


def to_plain(tex: str) -> str:
    """LaTeX abstract to arXiv text: accents to UTF-8, paper macros to standard TeX math."""
    for a, b in ACCENTS:
        tex = tex.replace(a, b)
    tex = tex.replace(r"\noindent", "")
    tex = re.sub(r"\\E(?![A-Za-z])", r"\\mathbb{E}", tex)
    tex = re.sub(r"\\F(?![A-Za-z])", r"\\mathcal{F}", tex)
    tex = re.sub(r"\\texttt\{([^}]*)\}", r"\1", tex)
    tex = tex.replace("~", " ").replace("---", "—").replace("--", "–")
    return re.sub(r"\s+", " ", tex).strip()


def page_count(pdf: Path) -> str:
    try:
        info = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True, check=True).stdout
        return re.search(r"Pages:\s+(\d+)", info).group(1)
    except (OSError, subprocess.CalledProcessError, AttributeError):
        return "?"


out = ["# arXiv replacement notes", "",
       "Generated by `make_notes.py`; `build.sh` writes the tarballs to `papers/dist/`.", ""]
for key, arxiv_id, ver, title in PAPERS:
    src = (BASE / key / f"{key}.tex").read_text(encoding="utf-8")
    abstract = to_plain(re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", src, re.S).group(1))
    if len(abstract) > ABSTRACT_LIMIT:
        raise SystemExit(f"{key}: abstract is {len(abstract)} characters, over arXiv's {ABSTRACT_LIMIT}")
    out += [
        f"## arXiv:{arxiv_id} → {ver}",
        "",
        f"**Upload:** `dist/{key}-arxiv.tar.gz` (`{key}.tex` + `mathfin-paper.sty`; pdflatex).",
        "",
        f"**Title** (unchanged): {title}",
        "",
        f"**Abstract** ({len(abstract)} characters; arXiv limit {ABSTRACT_LIMIT}):",
        "",
        "```",
        abstract,
        "```",
        "",
        "**Comments:**",
        "",
        "```",
        COMMENTS[key].format(pages=page_count(BASE / key / f"{key}.pdf")),
        "```",
        "",
    ]
(BASE / "arxiv-submission-notes.md").write_text("\n".join(out), encoding="utf-8")
print("wrote arxiv-submission-notes.md")
